#+title: 🤖 Робот: Руководство пользователя
#+language: ru

* Помощь

Чтобы изучить доступные команды, напишите ~!помощь~.

* Казино

Если вы хотите попытать удачу, вы можете рискнуть бросить кости.

Используйте команду ~!кости <ставка>~. Робот бросит кости, затем
бросайте свои. Если вы выкините кости с большим значением - получите
выигрыш. В случае ничьей, ставка возвращается. Если бот выкинет
больше, чем вы — он заберет ваши деньги.

* Драка

Вы можете сражаться с другими пользователями. Если вы одолели
оппонента, с некоторым шансом вы можете выбить из него случайный
предмет. Чтобы подраться с другим игроком, используйте команду
~!драка~ в ответ на его сообщение.

При победе вы получите рейтинг. Увидеть список самых успешных бойцов
можно с помощью команды ~!рейтинг~. Пользователи, занимающие первое,
второе и третье места в этом рейтинге получают небольшой прирост к
силе.

Самые сильные пользователей: ~!топ сильных~.

* Инвентарь

Инвентарь используется для хранения предметов: ~!инвентарь~. Каждый
предмет в инвентаре имеет свой номер. Команды которые взаимодействуют
с инвентарём принимают номер предмета (или несколько номеров) как
аргумент. Обычно это выглядит так: ~!команда <номер>~. Номера
обновляются, когда вы открываете инвентарь, и остаются такими же до
следующего вызова.

* Порядок

Порядок вещей в инвентаре имеет значение. Если вы используете команду,
которая должна выбрать предмет из инвентаря, используется первый
попавшийся. Предмет, находящийся в списке выше всех остальных, имеет
больший приоритет. Изменить порядок вещей можно с помощью команды
~!сорт <номера>~: предметы под указанными номерами переместятся в
самый верх инвентаря в указанном порядке.

Примеры таких команд: ~!рыбалка~, ~!еда~, ~!закинуть сеть~, ~!улов~,
~!отложить~.

Некоторые предметы, например, детали и деньги, имеют количество. Чтобы
сложить их в один слот, используйте команду ~!сложить~.

* Пол

Ненужные вещи можно выложить на пол: ~!дроп <номера>~. Предметы с пола
могут брать все пользователи: ~!взять <номера>~. Максимальное
количество вещей на полу - 10 штук. Чтобы предметов на полу не было
слишком много, самые старые удаляются при превышении этого количества,
а новые занимают их место.

* Крафт

Вы можете крафтить предметы при помощи команды ~!крафт <номера>~.
Порядок ингридиентов в рецепте имеет значение.

Рецепты:

- Две удочки одинакового уровня → Удочка уровня выше.
- Детали и удочка → Отремонтированная удочка.
- Удочка → Детали
- Смартфон → Детали
- Нож и животное → Мясо
- 50 деталей и 3 нити → Рыболовная сеть

* Прочность

У некоторых предметов есть запас прочности. Он отображается в
процентах. Когда прочность предмета падает ниже ~0%~, он исчезнет из
инвентаря.

* Рыбалка

Если у вас есть удочка, вы можете ловить рыбу: ~!рыбалка~. Пойманную
рыбу можно продать или съесть. Каждый уровень удочки дает ~10%~
прибавку к весу улова. Высокий уровень удачи повышает шанс выловить
рыбу.

Также, рыбу можно ловить с помощью рыболовной сети: ~!сеть~. Чем
дольше сеть находится в воде, тем больше шанс, что в неё попадётся
рыба.

Для дополнительного удобства, используйте ~!улов~. Пойманная рыба
будет отображена в виде списка с номерами, соответствующими позициям в
инвентаре. В конце списка можно увидеть суммарный вес и цену пойманной
рыбы.

* Энергия

Для использования некоторых команд требуется энергия. Со временем она
восстанавливается автоматически. Чтобы восполнить энергию, вы можете
есть еду: ~!съесть <номер>~. Увидеть свой уровень энергии можно с
помощью команды ~!энергия~.

Для того, чтобы не открывать инвентарь и не указывать номера каждый
раз, существует конвенциональная команда: ~!еда~. Вы съедите первый
попавшийся недорогой съедобный предмет.

* Экономика

Вы можете зарабатывать и тратить деньги. Отложить нужную сумму
(например, чтобы передать её другому игроку) можно с помощью команды
~!отложить <сумма>~. Заработать денег можно с помощью продажи деталей
и пойманной рыбы: ~!продать <номер>~. Чтобы увидеть суммарный баланс
не открывая инвентаря, используйте ~!баланс~.

Статистика об экономике беседы: ~!капитал~, ~!топ богатых~.

* Магазин

В магазине можно покупать предметы: ~!магазин~, ~!купить <номера>~.
Новые товары появляются случайным образом каждую минуту.

Если вы администратор, вы можете дать магазину название:
~!назвать магазин <название>~.

* Нейросети

Картинки, сгенерированные компьютерными машинами.

- ~!кот~
- ~!аниме~
- ~!фурри~
- ~!флаг~
- ~!чел~
- ~!лошадь~
- ~!арт~
- ~!авто~

* Профиль

Вы можете увидеть свои характеристики с помощью команды ~!профиль~.

Чтобы сменить имя, используйте ~!имя <новое имя>~. Максимальная длина
имени 16 символов. Эмодзи запрещены. Чтобы установить имя, бот даёт
минимальные права модератора беседы тому, кто использует эту команду.
Если вы уже модератор и вас назначил не бот - команда не сработает.

Вы можете установить статус и аватар:

- ~!статус <текст>~,
- ~!аватар (с приложенной к сообщению картинкой)~.

* Питомцы

Иногда в магазине продаются животные. Вы можете оставить их себе или
съесть. Чтобы назвать питомца, используйте команду ~!назвать <имя
питомца>~. Питомец будет отображаться в профиле, а также давать
небольшой бонус к силе в зависимости от его редкости.

* Смартфон

Если у вас есть смартфон, вы можете общаться при помощи СМС. Чтобы
увидеть входящие, напишите ~!смс~. Для отправки сообщений используется
та же команда: ~!смс <номер абонента> <сообщение>~. Посмотреть
мобильные номера пользователей, у которых есть телефон, используйте
~!контакты~.

Вы можете осуществить рассылку: ~!спам <сообщение>~. Сообщение придёт
всем, у кого есть смартфон.

* Кошки

Кошки пользователей беседы «нечего».

- ~!марсик~
- ~!муся~
- ~!каспер~
- ~!зевс~

* Администрация

Администратор может забанить или разбанить другого пользователя (в том
числе себя) на 2 часа: ~!бан~ или ~!разбан~ в ответ на сообщение.
Пользователь, находящийся под баном, не может использовать команды.

* Ежедневные

- ~!пара дня~
- ~!еблан дня~
- ~!админ дня~

* Другое

- ~!инфа <текст>~
- ~!кто <текст>~
- ~!список <текст>~
- ~!топ <текст>~
- ~!погода <место>~
- ~!калькулятор <выражение>~
- ~!пик~
- ~!сойжак~
- ~!данбору~
- ~!мыш~
- ~!тикток~
- ~!масюня~
- ~!паппи~
- ~!сима~
- ~!игра~
