#+title: 🤖 Робот: Руководство пользователя
#+language: ru

* 📖 Помощь

Чтобы изучить доступные команды, напишите ~!помощь~.

* 🎲 Кости

Если вы хотите попытать удачу, вы можете рискнуть бросить кости.

Используйте команду ~!кости <ставка>~. Робот бросит кости, затем
бросайте свои. Если вы выкините кости с большим значением - получите
выигрыш. В случае ничьей, ставка возвращается. Если бот выкинет
больше, чем вы - он заберёт ваши деньги.

* 🎰 Казино

Если вам не везёт в костях, сыграйте в слот-машину.

Для начала установите ставку: ~!слот <ставка>~. Затем отправьте эмодзи
~🎰~ в чат. Ставка спишется с вашего счёта автоматически. В случае
выигрышной комбинации, вам начислится выигрыш с некоторым множителем -
4, 8, 16, или 32.

* 🥊 Драка

Вы можете сражаться с другими пользователями. Если вы одолели
оппонента, с некоторым шансом вы можете выбить из него случайный
предмет. Чтобы подраться с другим игроком, используйте команду
~!драка~ в ответ на его сообщение.

При победе вы получите рейтинг. Увидеть список самых успешных бойцов
можно с помощью команды ~!рейтинг~. Пользователи, занимающие первое,
второе и третье места в этом рейтинге получают небольшой прирост к
силе. Пользователь с наивысшым рейтингом получает налог со всех продаж
в магазине.

Список самых сильных пользователей: ~!топ сильных~

* 🗄 Инвентарь

Инвентарь используется для хранения предметов: ~!инвентарь~. Каждый
предмет в инвентаре имеет свой номер. Команды которые взаимодействуют
с инвентарём принимают номер предмета (или несколько номеров) как
аргумент. Обычно это выглядит так: ~!команда <номер>~. Номера
обновляются, когда вы открываете инвентарь, и остаются такими же до
следующего вызова.

* 🗃 Порядок

Порядок вещей в инвентаре имеет значение. Если вы используете команду,
которая должна выбрать предмет из инвентаря (например, ~!рыбалка~,
~!еда~, ~!отложить~), используется первый попавшийся. Предмет,
находящийся в списке выше всех остальных, имеет больший приоритет.
Изменить порядок вещей можно с помощью команды ~!сорт <номер> ...~:
выбранные предметы переместятся наверх инвентаря в указанном порядке.

Некоторые предметы, например, детали и деньги, имеют количество. Чтобы
сложить их в один слот, используйте команду ~!сложить~. Отложить
нужное количество можно с помощью команды ~!отложить <номер>
<количество>~.

* 🗑 Пол

Ненужные вещи можно выложить на пол: ~!дроп <номер> ...~. Предметы с
пола могут брать все пользователи: ~!взять <номер> ...~. Максимальное
количество вещей на полу - 10 штук. Чтобы предметов на полу не было
слишком много, старые удаляются при превышении этого количества, а
новые занимают их место.

* 🛠 Крафт

Вы можете крафтить предметы при помощи команды ~!крафт <номер> ...~.
Порядок ингридиентов в рецепте имеет значение.

+ Две удочки одинакового уровня → Удочка уровня выше
+ Детали и удочка → Отремонтированная удочка
+ Удочка → Детали
+ Нож и животное → Мясо

* ⚙️ Прочность

У некоторых предметов есть запас прочности. Он отображается в
процентах. Если прочность предмета упадёт ниже ~0%~, он исчезнет из
инвентаря.

* 🎣 Рыбалка

Если у вас есть удочка, вы можете ловить рыбу: ~!рыбалка~. Пойманную
рыбу можно продать или съесть. Каждый уровень удочки дает прибавку к
весу улова. Высокий уровень удачи повышает шанс выловить рыбу.

* 🏡 Ферма

У каждого игрока есть ~!ферма~. На ферме можно выращивать растения на
еду или продажу. Каждый день цена растений меняется: ~!цены~. Посадить
растение можно с помощью команды ~!посадить <номер> ...~. Когда
растения вырастут, их можно будет собрать: ~!урожай~. Если у вас
достаточно средств, ферму можно расширить: ~!апгрейд~.

* ⚡️ Энергия

Для использования некоторых команд требуется энергия. Со временем она
восстанавливается автоматически. Чтобы восполнить энергию, вы можете
есть еду: ~!съесть <номер> ...~. Увидеть свой уровень энергии можно с
помощью команды ~!энергия~.

Для того, чтобы не открывать инвентарь и не выбирать еду самому,
существует быстрая команда: ~!еда~. Вы съедите первый попавшийся
недорогой съедобный предмет.

* 🏦 Экономика

Вы можете зарабатывать и тратить деньги. Отложить нужную сумму
(например, чтобы передать её другому игроку) можно с помощью команды
~!отложить <сумма>~. Заработать денег можно с помощью продажи деталей
и пойманной рыбы: ~!продать <номер> ...~. Чтобы увидеть суммарный
баланс не открывая инвентаря, используйте ~!баланс~.

Статистика об экономике беседы: ~!капитал~, ~!топ богатых~.

* 🏪 Магазин

В магазине можно покупать предметы: ~!магазин~, ~!купить <номер> ...~.
Новые товары появляются случайным образом каждую минуту.

Вы можете устроиться в магазин на подработку. Если вы используете
команду ~!работа~, вы будете получать некоторый процент с покупок в
течение смены. Заработанные средства можно получить на почте.

Магазин можно переименовать: ~!назвать магазин <название>~.

* 📬 Почта

Чтобы отправить посылку, используйте команду ~!отправить <номер>~ в
ответ на сообщение пользователя. Посылки можно отправлять только
друзьям. Получить входящие отправления можно с помощью команды
~!почта~.

* ✉️ Письма

Вы можете написать письмо: ~!написать <текст>~. Написанное письмо
окажется в вашем инвентаре. Письмо можно ~!прочитать~ или ~!отправить~
другу.

* 🔮 Нейросети

Картинки, сгенерированные компьютерными машинами.

- ~!кот~
- ~!аниме~
- ~!флаг~
- ~!авто~

* 📇 Профиль

Вы можете увидеть свои характеристики с помощью команды ~!профиль~.

Чтобы сменить имя, используйте ~!имя <новое имя>~. Максимальная длина
имени 16 символов. Эмодзи запрещены. Чтобы установить имя, бот даёт
минимальные права модератора беседы тому, кто использует эту команду.
Если вы уже модератор и вас назначил не бот - команда не сработает.

Вы можете установить статус и аватар:

- ~!статус <текст>~,
- ~!аватар (с приложенной к сообщению картинкой)~.

* 🐕 Питомцы

В магазине можно приобрести питомца. Чтобы назвать питомца,
используйте команду ~!назвать <имя питомца>~. Питомец будет
отображаться в профиле, а также давать небольшой бонус к силе в
зависимости от его редкости.

* 😊 Репутация

Вы можете повышать или понижать репутацию другим игрокам. Чтобы
повысить или понизить репутацию другого пользователя, ответьте на его
сообщение ~+~ или ~-~. Чтобы проверить свою репутацию, используйте
~!репутация~.

* 👩‍💻 Команды

В бота можно добавить новую команду: ~!добавить <команда>|<текст>~. К
команде можно приложить картинку. Чтобы удалить команду, используйте
~!удалить <команда>~.

* 🐈 Кошки

Кошки пользователей беседы «нечего».

- ~!марсик~
- ~!муся~
- ~!каспер~
- ~!зевс~

* 📅 Ежедневные

- ~!пара дня~
- ~!еблан дня~
- ~!админ дня~

* ✨ Другое

- ~!инфа <текст>~
- ~!кто <текст>~
- ~!список <текст>~
- ~!топ <текст>~
- ~!погода <место>~
- ~!калькулятор <выражение>~
- ~!пик~
- ~!сойжак~
- ~!данбору~
- ~!игра~
- ~!дата~
- ~!выбор <вариант1> или <вариант2> ...~
- ~!новый год~
