package handlers

import (
	"regexp"

	tele "gopkg.in/telebot.v3"
)

// Handler is a central concept of this package.
// Each type intended to process Telegram events should implement Handler.
type Handler interface {
	// Match returns true if the handler should process the given
	// input. It must not have any side effects.
	Match(s string) bool

	// Handle processes a Telegram event, assuming matching input.
	Handle(c tele.Context) error

	// Self is generated by handlerplate.
	Self() HandlerID
}

//go:generate handlerplate basic.go calc.go daily.go game.go phone.go farm.go auction.go actions.go
//go:generate stringer -type=HandlerID -output=handlers_string.go

// re compiles s as a case-insensitive regular expression.
func re(s string) *regexp.Regexp {
	return regexp.MustCompile("(?i)" + s)
}
