insert into handlers_info
values
 ('*daily.Eblan', '!еблан дня'),
 ('*daily.Admin', '!админ дня'),
 ('*daily.Pair', '!пара дня'),
 ('*fun.Game', '!игры'),
 ('*fun.Infa', '!инфа'),
 ('*fun.Choose', '!выбор'),
 ('*fun.Weather', '!погода'),
 ('*fun.Calc', '!калькулятор'),
 ('*fun.Name', '!имя'),
 ('*fun.Who', '!кто'),
 ('*fun.List', '!список'),
 ('*fun.Top', '!топ'),
 ('*fun.Clock', '!время'),
 ('*fun.Date', '!дата'),
 ('*fun.NewYear', '!новый год'),
 ('*fun.Photon', '!фотон'),
 ('*fun.Avatar', '!аватар'),
 ('*pictures.Pic', '!пик'),
 ('*pictures.Casper', '!каспер'),
 ('*pictures.Zeus', '!зевс'),
 ('*pictures.Mouse', '!мышь'),
 ('*pictures.Tiktok', '!тикток'),
 ('*pictures.Hello', '!привет'),
 ('*pictures.Anime', '!аниме'),
 ('*pictures.Furry', '!фурри'),
 ('*pictures.Flag', '!флаг'),
 ('*pictures.Car', '!машина'),
 ('*pictures.Soy', '!сой'),
 ('*pictures.Danbooru', '!данбору'),
 ('*pictures.Fap', '!драчить'),
 ('*pictures.Masyunya', '!масюня'),
 ('*pictures.Poppy', '!паппи'),
 ('*pictures.Sima', '!сима'),
 ('*pictures.Cat', '!кот'),
 ('*command.Add', 'добавить команду'),
 ('*command.Remove', 'убрать команду'),
 ('*command.Use', 'использовать команду'),
 ('*fun.Speak', 'w s any'),
 ('*pictures.Basili', '!кошки василия'),
 ('*fun.TurnOn', '!вкл'),
 ('*fun.TurnOff', '!выкл'),
 ('*pictures.FromDir', 'картинки'),
 ('*pictures.FromStickerPack', 'стикеры')
 on conflict (handler)
 do update set usage = excluded.usage;
